name: Update AKS operator in rancher/rancher
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to use for GitHub action workflow"
        required: true
        default: "master"
      rancher_ref:
        description: "Submit PR against the following rancher/rancher branch (e.g. release/v2.7)"
        required: true
        default: "release/v2.7"
      new_aks:
        description: "New AKS operator version (e.g. 1.1.0-rc2), don't include the 'v'"
        required: true
        default: ""

env:
  GOARCH: amd64
  CGO_ENABLED: 0
  SETUP_GO_VERSION: '1.20.*'

jobs:
  update-rancher-dep:
    uses: alexander-demicev/hostedprovidersactions/.github/workflows/update-rancher-dep.yaml@main
    with:
      ref: ${{ github.event.inputs.ref }}
      rancher_ref: ${{ github.event.inputs.rancher_ref }}
      new_operator_version: ${{ github.event.inputs.new_aks }}
      operator_repo: github.com/rancher/aks-operator
    secrets:
      token: ${{secrets.CI_BOT_TOKEN}}
