---
name: "Update AKS Operator version in Rancher" 

on:
  workflow_dispatch:
    inputs:
      rancher-branch:
        description: Rancher branch
        required: true
        default: release/v2.7
      aks-operator-tag:
        description: AKS Operator release tag
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2
      - uses: tibdex/github-app-token@v1.8
        id: generate_token
        with:
          app_id: ${{ secrets.HOSTEDPROVIDERS_BOT_APP_ID }}
          private_key: ${{ secrets.HOSTEDPROVIDERS_BOT_APP_PRIVKEY }}
      - name: Update aks operator dependency in rancher
        run: "updatecli apply --config ./.updatecli/configs/bump-rancher-dep.yaml --debug"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ secrets.HOSTEDPROVIDERS_BOT_GITHUB_ACTOR }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          UPDATECLI_RANCHER_BRANCH: ${{ github.event.inputs.rancher-branch }}
          UPDATECLI_AKS_OPERATOR_TAG: ${{ github.event.inputs.aks-operator-tag }}
